<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block partner-portal">
        <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")
            ->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
    <h1 class="partner-portal-welcome"><?= $block->escapeHtml(__('Welcome back to PwC')) ?></h1>
    <h2 class="partner-portal-partner"><?= $block->escapeHtml(__('Partner Portal')) ?></h2>
    <ul class="partner-portal--list-wrapper">
        <li><?= $block->escapeHtml(__('Search Products')) ?></li>
        <li><?= $block->escapeHtml(__('Request Sample')) ?></li>
        <li><?= $block->escapeHtml(__('Place Order')) ?></li>
        <li><?= $block->escapeHtml(__('Order Tracking')) ?></li>
    </ul>
    <picture>
        <img srcset=" <?php echo $this->getViewFileUrl('images/NoPath@2x.png 2x'); ?>"
        src="<?php echo $this->getViewFileUrl('images/NoPath.png'); ?>" />
    </picture>
</div>

<div class="block block-customer-login">
    <div class="block-customer-login--wrapper">
    <strong id="block-customer-login-heading" class="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Login')) ?></strong>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login"
                action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                method="post"
                id="login-form"
                data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Company Email ID')) ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                                <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                id="email" type="email" class="input-text"
                                title="<?= $block->escapeHtmlAttr(__('Company Email ID')) ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                placeholder= "<?= $block->escapeHtml(__('Company Email ID')) ?>"
                                data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                        <div class="control">
                            <input name="login[password]" type="password"
                                <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                class="input-text" id="pass"
                                title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                placeholder= "<?= $block->escapeHtml(__('Password')) ?>"
                                data-validate="{required:true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button></div>
                        <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    </div>
                    <div class="signup">
                        <span><?php echo $block->escapeHtml(__("Don't have an account")) ?></span>
                        <a class="signup-link" href="<?php echo $this->getUrl("customer/account/create/");?>"><?php echo __('Sign up')?></a>
                    </div>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                }
            }
        }
    </script>
</div>
