<div class="header content">
<?php echo $this->getChildHtml("logo"); ?>
<?php echo $this->getChildHtml("nav"); ?>
<?php echo $this->getChildHtml("topSearch"); ?>
<ul class="right-menu-options">
    <li><a href="/"><span class="icon icon-bell"></span><span class="content"><?php echo __("Notification") ?></span></a></li>
    <li><a href="/"><span class="icon icon-user"></span><span class="content"><?php echo __("My Profile") ?></span></a></li>
    <li><a href="/"><span class="icon icon-dollar-symbol"></span><span class="content"><?php echo __("Currency") ?></span></a></li>
    <li><a href="/"><span class="icon icon-846423"></span><span class="content"><?php echo __("Cart") ?></span></a></li>
</ul>
</div>